### ISSUE TITLE
vm is not updated on apply

### ISSUE THREAD

**Issue by ekle** [terraform-providers/terraform-provider-oneandone#1] opened 2017-06-28 09:05 UTC
### Terraform Version
Terraform v0.9.9

### Affected Resource(s)
- oneandone_server

### Expected Behavior
vm is changed

### Actual Behavior
the vm is not changed

### Steps to Reproduce
1. create a `oneandone_server` resource
2. `terraform apply`
3. change a value like `vcores` or `ram`
4. `terraform apply`
terraform states that it has updated the vm but the vm is not changed:
```
 terraform apply
oneandone_server.server3: Refreshing state... (ID: FA40...)
oneandone_server.server3: Modifying... (ID: FA406...)
  ram:              "8" => "4"
oneandone_server.server3: Modifications complete (ID: FA406AC0....)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by jasminSPC** [comment] 2017-06-28 09:38
@ekle The issue is confirmed and we are fixing it. I will keep you updated once it is available.

**Comment by jasminSPC** [comment] 2017-06-28 21:45
@ekle the fix has been pushed to the repo.

**Closed** 2017-07-13 11:12 UTC
